# Generated by Django 5.0.6 on 2024-06-14 04:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_warehouse"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Warehouse",
        ),
    ]
