# Generated by Django 5.0.6 on 2024-06-14 04:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_delete_warehouse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
    ]
