# Generated by Django 5.0.6 on 2024-06-14 05:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0009_alter_item_category"),
    ]

    operations = []
